@startuml
component "API 서비스"
package "데이터 저장소" {
component "데이터 라우팅 서비스"
component "배치 서비스"
database "데이터 노드(주)" as dn0
database "데이터 노드(부)" as dn1
database "데이터 노드(부)" as dn2
"데이터 라우팅 서비스" <-r-> "배치 서비스" : (2) 배치 서비스를 참조하여 주 노드 선정
dn0 <--> "데이터 라우팅 서비스" : (3) 데이터를 주 노드에 전송
"배치 서비스" <-d-> dn0 : heartbeat
"배치 서비스" <-d-> dn1 : heartbeat
"배치 서비스" <-d-> dn2 : heartbeat
dn0 -d-> dn1 : (4) 데이터 다중화
dn0 -d-> dn2  : (4) 데이터 다중화
}

"API 서비스" ---> "데이터 라우팅 서비스" : (1) 데이터 기록
"API 서비스" <--- "데이터 라우팅 서비스" : (5) 객체 ID를 실어 응답

@enduml