@startuml
 "소비자 A" -> 코디네이터 : 1a. heartbeat
 코디네이터 --> "소비자 A" : 1b. heartbeat ack
 "소비자 B" -> 코디네이터 : 2. 그룹 합류 요청
 "소비자 A" -> 코디네이터 : 3a. heartbeat
 코디네이터 --> "소비자 A" : 3b. 응답(소비자 재조정 필요, 그룹에 합류할 것)
 "소비자 A" -> 코디네이터 : 4a. 그룹 잔류 요청
 코디네이터 --> "소비자 A" : 4b. 응답(비 리더로 그룹에 정상 합류)
 코디네이터 --> "소비자 B" : 4b. 응답(리더로 그룹에 합류, 그룹 멤버 A,B)
 "소비자 A" -> 코디네이터 : 5. 그룹 동기화 요청
 "소비자 B" -> 코디네이터 : 5. 그룹 동기화 요청
 코디네이터 --> "소비자 A" : 그룹 동기화(A에 파티션 1,3 배치)
 코디네이터 --> "소비자 B" : 그룹 동기화(B에 파티션 2,4 배치)
 @enduml