 @startuml
 autonumber
 "소비자 A" -> 코디네이터 : heartbeat
 코디네이터 --> "소비자 A" : heartbeat ack

 "소비자 B" -> 코디네이터 : heartbeat
 코디네이터 --> "소비자 B" : heartbeat ack
 "소비자 A" -> 코디네이터 : 그룹 탈퇴 요청
 코디네이터 --> "소비자 A" : 그룹 탈퇴 요청 승인
 "소비자 B" -> 코디네이터 : heartbeat
 코디네이터 --> "소비자 B" : heartbeat ack(소비자 재조정이 필요하므로 그룹 재합류 요청)
 "소비자 B" -> 코디네이터 : 그룹 합류 요청
 코디네이터 --> "소비자 B" : 응답(리더로 그룹에 합류, 멤버 B)
 "소비자 B" -> 코디네이터 : 그룹 동기화 요청
 코디네이터 --> "소비자 B" : 그룹 동기화(B에 파티션 1,2,3,4 배치)
 @enduml