@startuml PostUploadClient
actor 클라이언트
component "백엔드" as BE
database "SQL DB" as SQL
folder "Object Store" as S3

클라이언트 -> BE : 게시물 POST (텍스트)
BE -> SQL : 저장
BE --> 클라이언트 : post_id
클라이언트 -> S3 : 이미지 업로드
@enduml
