@startuml
autonumber
업스트림 <- "집계 서비스 노드" : 이벤트 수집
업스트림 -> "집계 서비스 노드" : 오프셋 100부터 소비
"집계 서비스 노드" -> "집계 서비스 노드" : 100부터 110까지의 이벤트 집계
"집계 서비스 노드" -> 다운스트림 : 집계 결과 전송
다운스트림 -> "집계 서비스 노드" : 수신 응답
"집계 서비스 노드" -> 업스트림 !! : 110까지 소비하였음을 응답
@enduml