@startuml
file Policy
component Cache
Policy -right-> Cache : 1
component AlertManager
Cache <-down-> AlertManager : 2
database AlertStorage
AlertManager <-left-> AlertStorage : 4
component QueryService
AlertManager -down-> QueryService : 3
queue Kafka
AlertManager -right-> Kafka : 5
component Consumer
Consumer -left-> Kafka : 6
component Email
component SMS
component PagerDuty
component Https
Email -[hidden]down- SMS
SMS -[hidden]down- PagerDuty
PagerDuty -[hidden]down- Https

Consumer -right-> Email
Consumer -right-> SMS
Consumer -right-> PagerDuty
Consumer -right-> Https
@endmul