@startuml
component "지표 출처" as source
component "지표 수집기" as collector
database "시계열\n데이터베이스" as db
component "질의 시스템" as query
component "시각화 시스템" as viewer
component "경보 시스템" as alert
component "이메일" as email
component "단문 메시지" as sms
component "PagerDuty" as pager
component "HTTPS 서비스\n엔드포인트" as https

source -right-> collector
collector -right-> db
query -left-> db
viewer -up-> query : query
alert -down-> query

alert -up-> email
alert -up-> sms
alert -up-> pager
alert -up-> https
@enduml