@startuml
autonumber
업스트림 <- "집계 서비스 노드" : 이벤트 수집
업스트림 -> "집계 서비스 노드" : 오프셋 100부터 소비
"집계 서비스 노드" -> "HDFS/S3" : 오프셋 확인
"집계 서비스 노드" -> "집계 서비스 노드" : 100부터 110까지의 이벤트 집계
== transaction ==
"집계 서비스 노드" -> 다운스트림 : 집계 결과 전송
"집계 서비스 노드" -> "HDFS/S3" : 오프셋 저장
다운스트림 -> "집계 서비스 노드" : 수신 응답
== transaction ==
"집계 서비스 노드" -> 업스트림 : 업스트림에 새 오프셋 100 응답
@enduml